version: '3.7'
services:
  deploy-static-app:
    container_name: deploy-static-app
    image: leaweibel/deploy-static-app 

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: